### ISSUE TITLE
Auto fill fields on advanced search doesn't work

### ISSUE THREAD

**Issue by psalido** [Daniel-KM/Omeka-S-module-Reference#11]
In Reference module, version 3.4.13, it was possible get value list for fields configured in References:

![image](https://user-images.githubusercontent.com/3009909/87861551-994c5900-c947-11ea-9d29-890d39ff9869.png)

In current version 3.4.21 javascript code is unchanged, but module doesn't work with URLs with "output" parameter:

https://{server}/s/{siteslug}/reference/{field:prop}?output=json

Thus, value list for configured fields is not show on advanced search form.

In Readme.md , under "Usage", says:
"The results are available via json too via the module [ApiInfo]."

After install this module, URL remain without show correct data format.

**Comment by Daniel-KM** [comment]
Sorry to answer late, but this feature has been moved to /api/references.

**Comment by Daniel-KM** [comment]
Furthermore, the advanced search issue has been moved to module [Advanced Search Plus](https://github.com/Daniel-KM/Omeka-S-module-AdvancedSearchPlus) for Omeka 3.
