### ISSUE TITLE
General settings problem

### ISSUE THREAD

**Issue by meriotb** [Daniel-KM/Omeka-S-module-Reference#16]
Hi,
I have the module installed with the latest version 3.4.38.3.

When in the general settings I check the option 'Index reference metadata', the following error is generated:
ParseError
syntax error, unexpected ')'
Détails : 
ParseError: syntax error, unexpected ')' in /applis/omekas/home/www/omeka-s/modules/Reference/src/Job/UpdateReferenceMetadata.php:48

The line in question is the following:
$this->logger->notice(
            'Starting creation of reference metadata.', // @translate
        );

Removing the comma solves the problem.

**Comment by Daniel-KM** [comment]
Ok, it depends on version of php. It's fixed in last version.
