### ISSUE TITLE
Upgrade from 3.4.23.3 version to 3.4.29.3 does not work

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-Reference#18]
I tried to upgrade this module directly from 3.4.23.3 version to 3.4.29.3. 

Module was not working (no reference displayed). I upgrade release from release without skipping versions and it is working now.

I just post this to warn people who could face the same issue.

**Comment by Daniel-KM** [comment]
Thanks, fixed.

**Comment by mufticsanjin** [comment]
Hi, I am having a similar issue trying to upgrade from 3.4.32.3 to 3.4.39.3 (and 3.4.40.3) but I also get an issue where all page Reference Blocks that have been made get just a "There is no references". I tried to go release by release, so it seems like all works until 3.4.34.3 but when it gets to 3.4.35.3 it fails. I have not customised the module in anyway. I am running Omeka 3.2.1. I couldn't find anything in the logs to assist with the error.

**Comment by pprw** [comment]
During my tests, I uninstalled completely the module.
