### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-Reference#3]
My site is in French (set in global settings). However I have a not translated title for each glossary:

> Browse items by "Articles par leurs années de publication" (43 headings)

It is strange because the file fr.po contains the correct translation.

**Comment by Daniel-KM** [comment]
You can set the title via the blocks (site pages). 
I just updated the language in 3.4.10.

**Comment by Daniel-KM** [comment]
You can set the title via the blocks (site pages). The case changed.
I just updated the language in 3.4.10.

**Comment by Daniel-KM** [comment]
You may clean the cache of Apache or inside /tmp, the translations are cached for one hour or more.
For the other point, I have to create a new block for it.

**Comment by Daniel-KM** [comment]
I created the block for the index in https://github.com/Daniel-KM/Omeka-S-module-Reference/commit/bd0cef04e237e2bba971d2d55c76239316e7d0e9, but the related pages are not created automatically, so it's a work in progress.
