### ISSUE TITLE
Duplicate custom labels causes failure to save

### ISSUE THREAD

**Issue by hxsllc** [Daniel-KM/Omeka-S-module-Reference#5]
I don't know exactly if it's a bug, but I just encountered this scenario on Omeka-S v1.2, Reference v3.4.9.

I previously had dcterms:relation enabled in Reference module and labeled as slug:movements, label:Movements.

I unchecked it and then modified dcterms:audience to be the same. 

After saving, it did not report an error, but it did not store the changes.

Once I manually set dcterms:relation fields back to original (or I assume any other value), then it successfully saved the changes to dcterms:audience.

So it seems to me from the outside there is some unstated assumption in the code that there can be no "name clash" and it treats slugs and labels as unique. Now that I type it, it seems relatively obvious that would be the case with slugs... so I think maybe it's just a UX issue about error message. Very minor.

**Comment by Daniel-KM** [comment]
Not sure if I understand your issue, but could you try the last release first?

**Comment by Daniel-KM** [comment]
Thanks, it is fixed in v3.4.11.
