### ISSUE TITLE
Linked metadata

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-Reference#6]
This module does not work for linked fields (for example if you indicate for item A another omeka item B as (DC)Creator and use Reference to display all creators, item B will not be showed in the creators list.)

Any plan to support linked fields in the futur?

**Comment by Daniel-KM** [comment]
It's an interesting feature, but yes, it works only for literals. I don't have plan in the short term for that, but I accept pull requests...

**Comment by Daniel-KM** [comment]
La fonctionnalité est implémentée dans la version 3.4.22.
