### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by zachwhalen** [Daniel-KM/Omeka-S-module-Reference#9]
Hi,

I've run into a problem installing (actually, upgrading) this module. Once I unpack these files, I get the following PHP fatal errors:

> Warning: require_once(/mysite/modules/Reference/vendor/autoload.php): failed to open stream: No such file or directory in /mysite/modules/Reference/Module.php on line 35
>
> Fatal error: require_once(): Failed opening required '/mysite/modules/Reference/vendor/autoload.php' (include_path='.:/opt/cpanel/ea-php72/root/usr/share/pear') in /mysite/modules/Reference/Module.php on line 35

Any thoughts?

**Comment by m-art-in** [comment]
Could you please discribe how you did the upgrade? Via the ZIP-File or Composer?

**Comment by zachwhalen** [comment]
@m-art-in Zip. I uploaded this module's zip file into my Modules folder and unzipped it there.

**Comment by zachwhalen** [comment]
I have read the documentation more carefully where I see that the scenario I encountered is covered in the section about using composer. Following those directions solved my problem. Nevermind!
